#!/bin/bash

set -e

REPOSITORIO_VERSION="1.1.0"
REPOSITORIO_DIST_FILE="Rex-Repositorio-${REPOSITORIO_VERSION}.tar.gz"
REPOSITORIO_DIST_URL="http://get.repositor.io/downloads/${REPOSITORIO_DIST_FILE}"

REXIFY_REPO_GPG_URL="http://rex.linux-files.org/RPM-GPG-KEY-REXIFY-REPO"


grab () {
  local url=$1
  local file=${2:-${1##*/}}

  cmd=( curl -R -L )
  cmd+=( -o "$file" )
  if [ -f "$file" ] ; then
    cmd+=( -z "$file" )
  fi
  cmd+=( "$url" )

  ( set -x ; "${cmd[@]}" )
}

cd "$(dirname "$0")"

grab "$REPOSITORIO_DIST_URL"
grab "$REXIFY_REPO_GPG_URL"
